version: '2.1'

services:
  db:
    build:
      context: ./db
    ports:
      - "1433:1433"
    healthcheck:
      test: [ "CMD", "/opt/mssql-tools/bin/sqlcmd", "-U", "sa", "-P", "password123!@#", "-Q", "select 1" ]
      interval: 5s
      retries: 20
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=password123!@#